#!/bin/sh
set -e

# this will check if the first argument is a flag
# but only works if all arguments require a hyphenated flag
# -v; -SL; -f arg; etc will work, but not arg1 arg2
if [ "$#" -eq 0 ] || [ "${1#-}" != "$1" ]; then
    set -- varnishd \
	    -F \
	    -f /etc/varnish/default.vcl \
	    -a http=:${VARNISH_HTTP_PORT:-80},HTTP \
	    -a proxy=:${VARNISH_PROXY_PORT:-8443},PROXY \
	    -p feature=+http2 \
	    -s malloc,$VARNISH_SIZE \
	    "$@"
fi

# wait for vcache_mgr_agent to complete config template resolution
while [ ! -f /var/run/.vcache_ready ]; do
	echo "[varnish-entrypoint] waiting for initial config setup..."
	sleep 2
done

exec "$@"
