#!/bin/bash
cd /etc/varnish
echo "installing python virtual environment"
python3 -m venv .venv
source .venv/bin/activate
echo "installing python requirements"
pip install -r requirements.txt > /dev/null 2>&1
echo "running vanishtstats-exporter"
python varnishstats-exporter.py
exit $?
